package com.lazyman.timetennis.user;

import java.io.Serializable;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tt_user
 */
public class User implements Serializable {

    public static final String SYSTEM_USER = "timetennis";

    private String openId;

    private String nickname;

    private String wxNickname;

    private String avatar;

    private Boolean vip;

    private Date updateTime;

    private Boolean admin;

    private Integer balance;

    private Boolean accountant;

    private Boolean superAdmin;

    private Boolean arenaAdmin;

    private String phoneNumber;

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public Boolean isArenaAdmin() {
        return arenaAdmin;
    }

    public void setArenaAdmin(Boolean arenaAdmin) {
        this.arenaAdmin = arenaAdmin;
    }

    public Boolean isAccountant() {
        return accountant;
    }

    public Boolean isSuperAdmin() {
        return superAdmin;
    }


    public void setAccountant(Boolean accountant) {
        this.accountant = accountant;
    }

    public void setSuperAdmin(Boolean superAdmin) {
        this.superAdmin = superAdmin;
    }

    public Integer getBalance() {
        return balance;
    }

    public void setBalance(Integer balance) {
        this.balance = balance;
    }

    public Boolean getAdmin() {
        return admin;
    }

    public void setAdmin(Boolean admin) {
        this.admin = admin;
    }

    public String getOpenId() {
        return openId;
    }

    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    public String getWxNickname() {
        return wxNickname;
    }

    public void setWxNickname(String wxNickname) {
        this.wxNickname = wxNickname == null ? null : wxNickname.trim();
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    public Boolean getVip() {
        return vip;
    }

    public void setVip(Boolean vip) {
        this.vip = vip;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public Boolean isSystem() {
        return SYSTEM_USER.equals(this.getOpenId());
    }
}