spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lewin?useUnicode=true&characterEncoding=UTF-8
    username: timetennis
    password: ${wx.mysql-password}

wx:
  pay-use-sandbox: true
  pay-notify-url: https://www.xiaoqicloud.cn/lewin/pay/notify
