spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lewin?useUnicode=true&characterEncoding=UTF-8
    username: timetennis
    password: ${wx.mysql-password}
logging:
  config: classpath:logback-spring-production.xml

wx:
  pay-use-sandbox: false
  images-path: /home/chenxiaoqi/app-data/lewin/images
