spring:
  messages:
    basename: i18n.Message
    encoding: UTF-8
  jackson:
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.20:3306/timetennis?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: chenxiaoqi
    password: chenxiaoqi
    hikari:
      connection-test-query: select 1
      idle-timeout: 60000
      max-lifetime: 300000
      maximum-pool-size: 5
      minimum-idle: 1
  mvc:
    static-path-pattern: /images/**
  resources:
    static-locations: file:${wx.images-path}
  servlet:
    multipart:
      max-request-size: 10MB
      location: tmp
server:
  port: 8080
  address: 0.0.0.0

wx:
  app-id: wx632c18a7a2865f2d
  secret: ${wx.app-secret}
  mch-id: 1602854290
  pay-sign-key: ${wx.pay-secret}
  pay-use-sandbox: true
  pay-sp-bill-create-ip: 124.70.154.176
  pay-notify-url: https://vn.xiaoqicloud.cn/pay/notify
  pay-expire-minutes: 5
  stat-cron: 0 0 1 1 1/1 ?
  cancel-times-limit: 2
  images-path: images
  default-arena-id: 2
  default-court-id: 7