package com.lazyman.timetennis.log;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

@Mapper
public interface OperationMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated
     */
    int insert(Operation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation
     *
     * @mbg.generated
     * @param start
     */
    List<Operation> selectAll(@Param("start") Date start);

}