package com.lazyman.timetennis.booking;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.lazyman.timetennis.user.User;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class Booking implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_booking.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_booking.open_id
     *
     * @mbg.generated
     */
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_booking.date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_booking.start
     *
     * @mbg.generated
     */
    private Integer start;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_booking.end
     *
     * @mbg.generated
     */
    private Integer end;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_booking.charged
     *
     * @mbg.generated
     */
    private Boolean charged;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_booking.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    private User owner;

    private Integer fee;

    private List<User> shareUsers;

    public List<User> getShareUsers() {
        return shareUsers;
    }

    public void setShareUsers(List<User> shareUsers) {
        this.shareUsers = shareUsers;
    }

    public Integer getFee() {
        return fee;
    }

    public void setFee(Integer fee) {
        this.fee = fee;
    }

    private boolean cancelAble;

    public boolean isCancelAble() {
        return cancelAble;
    }

    public void setCancelAble(boolean cancelAble) {
        this.cancelAble = cancelAble;
    }

    public User getOwner() {
        return owner;
    }

    public void setOwner(User owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_booking.id
     *
     * @return the value of tt_booking.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_booking.id
     *
     * @param id the value for tt_booking.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_booking.open_id
     *
     * @return the value of tt_booking.open_id
     *
     * @mbg.generated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_booking.open_id
     *
     * @param openId the value for tt_booking.open_id
     *
     * @mbg.generated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_booking.date
     *
     * @return the value of tt_booking.date
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_booking.date
     *
     * @param date the value for tt_booking.date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_booking.start
     *
     * @return the value of tt_booking.start
     *
     * @mbg.generated
     */
    public Integer getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_booking.start
     *
     * @param start the value for tt_booking.start
     *
     * @mbg.generated
     */
    public void setStart(Integer start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_booking.end
     *
     * @return the value of tt_booking.end
     *
     * @mbg.generated
     */
    public Integer getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_booking.end
     *
     * @param end the value for tt_booking.end
     *
     * @mbg.generated
     */
    public void setEnd(Integer end) {
        this.end = end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_booking.charged
     *
     * @return the value of tt_booking.charged
     *
     * @mbg.generated
     */
    public Boolean getCharged() {
        return charged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_booking.charged
     *
     * @param charged the value for tt_booking.charged
     *
     * @mbg.generated
     */
    public void setCharged(Boolean charged) {
        this.charged = charged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_booking.update_time
     *
     * @return the value of tt_booking.update_time
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_booking.update_time
     *
     * @param updateTime the value for tt_booking.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_booking
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Booking other = (Booking) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOpenId() == null ? other.getOpenId() == null : this.getOpenId().equals(other.getOpenId()))
            && (this.getDate() == null ? other.getDate() == null : this.getDate().equals(other.getDate()))
            && (this.getStart() == null ? other.getStart() == null : this.getStart().equals(other.getStart()))
            && (this.getEnd() == null ? other.getEnd() == null : this.getEnd().equals(other.getEnd()))
            && (this.getCharged() == null ? other.getCharged() == null : this.getCharged().equals(other.getCharged()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_booking
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOpenId() == null) ? 0 : getOpenId().hashCode());
        result = prime * result + ((getDate() == null) ? 0 : getDate().hashCode());
        result = prime * result + ((getStart() == null) ? 0 : getStart().hashCode());
        result = prime * result + ((getEnd() == null) ? 0 : getEnd().hashCode());
        result = prime * result + ((getCharged() == null) ? 0 : getCharged().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}