package com.lazyman.timetennis.booking;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface BookingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_booking
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_booking
     *
     * @mbg.generated
     */
    int insert(Booking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_booking
     *
     * @mbg.generated
     */
    Booking selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_booking
     *
     * @mbg.generated
     */
    List<Booking> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_booking
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Booking record);


    List<Booking> queryByDate(@Param("date") Date date);

    List<Booking> queryInRange(@Param("start")Date start,@Param("end") Date end);
}