spring:
  messages:
    basename: i18n.Message
    encoding: UTF-8
  jackson:
    time-zone: GMT+8
  datasource:
    url: ENC(jdbc:h2:tcp://localhost:8043/./db/WiseSupport)
    username: sa
    driver-class-name: org.h2.Driver
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
  http:
    log-request-details: true
  mvc:
    locale-resolver: fixed
    static-path-pattern: /statics/**
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true


management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["*"]

swagger:
  enabled: true

springfox:
  documentation:
    swagger:
      v2:
        path: /swagger-resources/v2/api-docs
server:
  port: 8080
