spring:
  messages:
    basename: i18n.Message
    encoding: UTF-8
  jackson:
    time-zone: GMT+8
  datasource:
    url: ENC(jdbc:h2:tcp://localhost:8043/./db/WiseSupport)
    username: sa
    driver-class-name: org.h2.Driver
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
  http:
    log-request-details: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never
  mvc:
    locale-resolver: fixed
    static-path-pattern: /statics/**
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          jobStore:
            clusterCheckinInterval: 20000
            isClustered: true
  task:
    execution:
      pool:
        core-size: 1
        max-size: 2
        queue-capacity: 1
    scheduling:
      pool:
        size: 1
  cache:
    type: simple
  batch:
    initialize-schema: never
    job:
      enabled: true
      names: importJob
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["*"]

swagger:
  enabled: true

springfox:
  documentation:
    swagger:
      v2:
        path: /swagger-resources/v2/api-docs
server:
  port: 8443
  ssl:
    enabled: true
    key-password: 123456
    key-store-password: 123456
    key-store: classpath:ssl/tomcat.keystore
    key-alias: lazyman
    key-store-type: jks
    client-auth: need
    trust-store: classpath:ssl/tomcat.keystore
    trust-store-password: 123456
    trust-store-type: jks
    trust-store-provider: SUN
